# Generated by Django 6.0.4 on 2026-05-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_utm_content_lead_utm_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новая заявка'), ('target', 'Целевая'), ('spam', 'Спам'), ('no_answer', 'Не дозвон')], default='new', max_length=20),
        ),
    ]
