# Generated by Django 6.0.4 on 2026-05-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='page_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
