# Generated by Django 6.0.4 on 2026-05-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Алмазное бурение', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('default_phone', models.CharField(blank=True, max_length=30)),
                ('default_address', models.CharField(blank=True, max_length=255)),
                ('homepage_title', models.CharField(blank=True, max_length=255)),
                ('homepage_description', models.TextField(blank=True)),
                ('homepage_keywords', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telegram', models.CharField(blank=True, max_length=255)),
                ('whatsapp', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
