# Generated by Django 6.0.4 on 2026-05-26 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_hero_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettingsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.sitesettings')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
