# Generated by Django 6.0.4 on 2026-05-27 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettingsprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройка сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AlterModelOptions(
            name='sitesettingsprice',
            options={'ordering': ['sort_order'], 'verbose_name': 'Прайс-лист', 'verbose_name_plural': 'Прайс-листы'},
        ),
        migrations.AlterModelTable(
            name='sitesettings',
            table='site_settings',
        ),
    ]
