# Generated by Django 6.0.4 on 2026-05-27 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sitesettingsprice',
            table='site_settings_prices',
        ),
    ]
