# Generated by Django 6.0.4 on 2026-05-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesettingsprice_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingsprice',
            name='price_table_title',
            field=models.CharField(blank=True, default='Цены на услуги', max_length=255, verbose_name='Название таблицы цен'),
        ),
    ]
