# Generated by Django 6.0.4 on 2026-05-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettingsprice_price_table_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettingsprice',
            name='price_table_title',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_table_title',
            field=models.CharField(blank=True, default='Цены на услуги', max_length=255, verbose_name='Название таблицы цен'),
        ),
    ]
