# Generated by Django 6.0.4 on 2026-05-27 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sitesettingsprice_price_table_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='price_table_title',
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название таблицы')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tables', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'Таблица цен',
                'verbose_name_plural': 'Таблицы цен',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PriceTableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255, verbose_name='Услуга')),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='Ед. изм.')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pricetable')),
            ],
            options={
                'verbose_name': 'Строка таблицы',
                'verbose_name_plural': 'Строки таблицы',
                'ordering': ['sort_order'],
            },
        ),
        migrations.DeleteModel(
            name='SiteSettingsPrice',
        ),
    ]
