# Generated by Django 6.0.4 on 2026-05-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_sitesettings_price_table_title_pricetable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetable',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='pricetableitem',
            options={},
        ),
        migrations.AddField(
            model_name='pricetable',
            name='price_column_name',
            field=models.CharField(default='Цена', max_length=100),
        ),
        migrations.AddField(
            model_name='pricetable',
            name='service_column_name',
            field=models.CharField(default='Услуга', max_length=100),
        ),
        migrations.AddField(
            model_name='pricetable',
            name='show_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricetable',
            name='show_unit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricetable',
            name='unit_column_name',
            field=models.CharField(default='Ед. изм.', max_length=100),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pricetableitem',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pricetableitem',
            name='service',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pricetableitem',
            name='unit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
