# Generated by Django 6.0.4 on 2026-05-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pricetable_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_advantages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_text',
            field=models.TextField(blank=True),
        ),
    ]
