# Generated by Django 6.0.4 on 2026-05-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_homepage_advantages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_advantages_h2',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_text_h2',
            field=models.CharField(blank=True),
        ),
    ]
