# Generated by Django 6.0.4 on 2026-06-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_homepage_advantages_h2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='work-types/', verbose_name='Изображение')),
                ('button_text', models.CharField(default='Оставить заявку', max_length=100, verbose_name='Текст кнопки')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Выполняемая работа',
                'verbose_name_plural': 'Выполняемые работы',
                'ordering': ['sort_order'],
            },
        ),
    ]
