# Generated by Django 6.0.4 on 2026-06-09 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0013_city_is_main'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to='cities.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя организации'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=30, verbose_name='Второй телефон'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='Рабочее время'),
        ),
    ]
