# Generated by Django 6.0.4 on 2026-06-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenantprofile_address_alter_tenantprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantprofile',
            name='website',
        ),
    ]
