# Generated by Django 6.0.4 on 2026-06-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_tenantprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='max',
            field=models.CharField(blank=True, max_length=255, verbose_name='Max'),
        ),
    ]
