# Generated by Django 6.0.4 on 2026-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="h1_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="seo_keywords",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="h1_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
