# Generated by Django 6.0.4 on 2026-05-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_city_h1_title'),
        ('pages', '0003_seo_h1_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('base_content', models.TextField(help_text='Используй {city} для подстановки города')),
            ],
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='h1_title',
        ),
        migrations.AddConstraint(
            model_name='faq',
            constraint=models.UniqueConstraint(fields=('city', 'slug'), name='unique_city_faq_slug'),
        ),
        migrations.AddConstraint(
            model_name='servicepage',
            constraint=models.UniqueConstraint(fields=('city', 'slug'), name='unique_city_service_slug'),
        ),
    ]
