# Generated by Django 6.0.4 on 2026-05-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_servicetemplate_remove_servicepage_h1_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='h1_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
