# Generated by Django 6.0.4 on 2026-05-02 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_servicepage_h1_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('base_content', models.TextField()),
                ('page_type', models.CharField(choices=[('service', 'Service'), ('price', 'Price'), ('info', 'Info')], max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_templates', to='pages.servicetemplate')),
            ],
        ),
    ]
