# Generated by Django 6.0.4 on 2026-05-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_city_h1_title'),
        ('pages', '0006_pagetemplate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicepage',
            name='unique_city_service_slug',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.servicetemplate'),
        ),
        migrations.AddConstraint(
            model_name='servicepage',
            constraint=models.UniqueConstraint(fields=('city', 'service', 'slug'), name='unique_city_service_slug'),
        ),
    ]
