# Generated by Django 6.0.4 on 2026-05-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_servicepage_unique_city_service_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='service',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.servicetemplate'),
            preserve_default=False,
        ),
    ]
