# Generated by Django 6.0.4 on 2026-05-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_servicepage_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetemplate',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
