# Generated by Django 6.0.4 on 2026-05-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_pagetemplate_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
