# Generated by Django 6.0.4 on 2026-05-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_city_h1_title'),
        ('pages', '0010_servicepage_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industrial_zones', models.TextField(blank=True)),
                ('typical_concrete', models.CharField(blank=True, max_length=100)),
                ('price_range', models.CharField(blank=True, max_length=100)),
                ('portfolio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='servicepage',
            name='unique_city_service_slug',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.servicepage'),
        ),
        migrations.AddField(
            model_name='citydata',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cities.city'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.service'),
        ),
        migrations.AddConstraint(
            model_name='servicepage',
            constraint=models.UniqueConstraint(fields=('city', 'slug'), name='unique_city_slug'),
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='seo_keywords',
        ),
    ]
