# Generated by Django 6.0.4 on 2026-05-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_remove_city_h1_title'),
        ('pages', '0011_citydata_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagetemplate',
            name='service',
        ),
        migrations.RemoveConstraint(
            model_name='servicepage',
            name='unique_city_slug',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='h1_title',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='servicepage',
            constraint=models.UniqueConstraint(fields=('city', 'parent', 'slug'), name='unique_city_parent_slug'),
        ),
        migrations.DeleteModel(
            name='PageTemplate',
        ),
        migrations.DeleteModel(
            name='ServiceTemplate',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='h1_title',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
