# Generated by Django 6.0.4 on 2026-05-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_pagetemplate_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='no_index',
            field=models.BooleanField(default=False, verbose_name='Не индексировать'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='show_in_menu',
            field=models.BooleanField(default=True, verbose_name='Показывать в меню'),
        ),
    ]
