# Generated by Django 6.0.4 on 2026-05-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_servicepage_is_published_servicepage_no_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydata',
            name='competitors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='citydata',
            name='districts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='citydata',
            name='restrictions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='citydata',
            name='typical_thickness',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
