# Generated by Django 6.0.4 on 2026-05-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_citydata_competitors_citydata_districts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='no_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='show_in_menu',
            field=models.BooleanField(default=True),
        ),
    ]
