# Generated by Django 6.0.4 on 2026-05-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_servicepage_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_template', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content_template', models.TextField()),
                ('seo_title_template', models.CharField(max_length=255)),
                ('seo_description_template', models.TextField()),
            ],
        ),
    ]
