# Generated by Django 6.0.4 on 2026-05-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_servicetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplate',
            name='seo_keywords_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
