# Generated by Django 6.0.4 on 2026-05-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_servicetemplate_seo_keywords_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
