# Generated by Django 6.0.4 on 2026-05-11 20:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_servicepage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplate',
            name='h1_template',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.servicetemplate'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='show_in_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
