# Generated by Django 6.0.4 on 2026-05-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_servicetemplate_h1_template_servicetemplate_is_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
