# Generated by Django 6.0.4 on 2026-05-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_servicepage_is_main_servicepage_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='h1_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
