# Generated by Django 6.0.4 on 2026-05-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_servicepage_h1_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
