# Generated by Django 6.0.4 on 2026-05-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_faq_slug_alter_servicepage_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
