# Generated by Django 6.0.4 on 2026-05-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_servicepage_slug_alter_servicetemplate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
