# Generated by Django 6.0.4 on 2026-05-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_faq_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='h1_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
