# Generated by Django 6.0.4 on 2026-05-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_faq_h1_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='related_services',
            field=models.ManyToManyField(blank=True, related_name='related_faqs', to='pages.servicepage'),
        ),
    ]
