# Generated by Django 6.0.4 on 2026-05-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_faq_related_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_template', models.CharField(max_length=255)),
                ('answer_template', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
