# Generated by Django 6.0.4 on 2026-05-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_alter_city_slug'),
        ('pages', '0027_faqtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('cta', 'CTA'), ('trust', 'Trust'), ('price', 'Price'), ('review', 'Review')], default='text', max_length=50)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cities', models.ManyToManyField(blank=True, related_name='seo_blocks', to='cities.city')),
                ('services', models.ManyToManyField(blank=True, related_name='seo_blocks', to='pages.servicepage')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
