# Generated by Django 6.0.4 on 2026-05-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_seoblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydata',
            name='business_centers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='citydata',
            name='metro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='citydata',
            name='residential_complexes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='citydata',
            name='streets',
            field=models.TextField(blank=True),
        ),
    ]
