# Generated by Django 6.0.4 on 2026-05-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_alter_city_slug'),
        ('pages', '0029_citydata_business_centers_citydata_metro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictPageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_template', models.CharField(max_length=255)),
                ('content_template', models.TextField()),
                ('seo_title_template', models.CharField(max_length=255)),
                ('h1_template', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('population', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='cities.city')),
            ],
        ),
    ]
