# Generated by Django 6.0.4 on 2026-05-16 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_districtpagetemplate_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pages.district'),
        ),
    ]
