# Generated by Django 6.0.4 on 2026-05-17 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_alter_city_slug'),
        ('pages', '0033_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtpagetemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='districtpagetemplate',
            name='seo_description_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='districtpagetemplate',
            name='service_template',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='district_templates', to='pages.servicetemplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='districtpagetemplate',
            name='seo_title_template',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='DistrictServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.district')),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.servicepage')),
            ],
            options={
                'unique_together': {('district', 'service_page')},
            },
        ),
    ]
