# Generated by Django 6.0.4 on 2026-05-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_districtpagetemplate_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
