# Generated by Django 6.0.4 on 2026-05-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_serviceprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='hero_image',
        ),
    ]
