# Generated by Django 6.0.4 on 2026-05-26 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_remove_servicepage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='pages.servicetemplate'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliocase',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.CreateModel(
            name='ServiceTemplatePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pages.servicetemplate')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.DeleteModel(
            name='ServicePrice',
        ),
    ]
