# Generated by Django 6.0.4 on 2026-05-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_servicepage_template_alter_faq_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
