# Generated by Django 6.0.4 on 2026-05-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_globalfaq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalfaq',
            options={'ordering': ['sort_order'], 'verbose_name': 'FAQ главной страницы', 'verbose_name_plural': 'FAQ главной страницы'},
        ),
        migrations.AlterField(
            model_name='globalfaq',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='globalfaq',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='globalfaq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='globalfaq',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
