# Generated by Django 6.0.4 on 2026-06-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_alter_globalfaq_options_alter_globalfaq_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqtemplate',
            name='related_service_templates',
            field=models.ManyToManyField(blank=True, to='pages.servicetemplate'),
        ),
    ]
