# Generated by Django 6.0.4 on 2026-07-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_faqtemplate_related_service_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('answer', models.TextField()),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.TextField(blank=True)),
                ('h1_title', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('related_service_templates', models.ManyToManyField(blank=True, related_name='global_faqs', to='pages.servicetemplate')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
