# Generated by Django 6.0.4 on 2026-07-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_servicefaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefaq',
            name='h1_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
