# Generated by Django 6.0.4 on 2026-07-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_alter_servicefaq_h1_title_alter_servicefaq_seo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefaq',
            name='related_service_templates',
            field=models.ManyToManyField(blank=True, related_name='service_faqs', to='pages.servicetemplate'),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
