# Generated by Django 6.0.4 on 2026-07-15 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0015_city_choose_as_city_choose_as_h2_city_useful_and_more'),
        ('pages', '0044_alter_servicefaq_related_service_templates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Верхнее меню',
                'verbose_name_plural': 'Верхнее меню',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterField(
            model_name='faq',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='cities.city'),
        ),
        migrations.DeleteModel(
            name='ServiceFAQ',
        ),
    ]
