# Generated by Django 6.0.4 on 2026-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
