# Generated by Django 6.0.4 on 2026-04-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_city_seo_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='price_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
