# Generated by Django 6.0.4 on 2026-05-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_price_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
