# Generated by Django 6.0.4 on 2026-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0004_city_telegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="h1_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
