# Generated by Django 6.0.4 on 2026-05-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_city_h1_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='h1_title',
        ),
    ]
