# Generated by Django 6.0.4 on 2026-05-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_remove_city_h1_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='h1_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
