# Generated by Django 6.0.4 on 2026-05-06 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_city_h1_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='subdomain',
        ),
    ]
