# Generated by Django 6.0.4 on 2026-05-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_remove_city_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
