# Generated by Django 6.0.4 on 2026-05-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_alter_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='page_score',
            field=models.IntegerField(default=0),
        ),
    ]
