# Generated by Django 6.0.4 on 2026-05-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0010_city_page_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_oblast',
            field=models.CharField(default='Москве', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='name_where',
            field=models.CharField(default='Московской области', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
