# Generated by Django 6.0.4 on 2026-05-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_city_name_oblast_city_name_where'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_oblast_where',
            field=models.CharField(default='Московской области', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
