# Generated by Django 6.0.4 on 2026-06-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0012_city_name_oblast_where'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главный город'),
        ),
    ]
