# Generated by Django 6.0.4 on 2026-07-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0013_city_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='homepage_advantages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='homepage_advantages_h2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='homepage_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='homepage_text_h2',
            field=models.TextField(blank=True),
        ),
    ]
