# Generated by Django 6.0.4 on 2026-07-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0014_city_homepage_advantages_city_homepage_advantages_h2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='choose_as',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='choose_as_h2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='useful',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='useful_h2',
            field=models.TextField(blank=True),
        ),
    ]
